### ISSUE TITLE
WinForms trimming in .NET 7

### ISSUE THREAD

**Issue by YoshiRulz** [KarstSkarn/KasTAS#13]
https://github.com/KarstSkarn/KasTAS/blob/284f469a2f7e48bcfbe348496e0fa7378c50d685/README.md#L46
It seems this is no longer the case and it mostly works now. https://devblogs.microsoft.com/dotnet/winforms-enhancements-in-dotnet-7/#comwrappers-and-native-aot

**Comment by KarstSkarn** [comment]
First of all, thank you for letting me know about this!. 
Although I have been quite busy at work lately I did read about the possibility of trimming Windows Forms in .NET 7 and have been implementing it in a new code update. Apart from this I have added a couple of functions that I thought necessary and I will upload it soon.

I'm just worried that because of this it will lose compatibility with older versions of Win 10 and earlier systems (If I'm not mistaken).

**Comment by KarstSkarn** [comment]
It is updated now! I hope is this what you meant!
